// This enum was generated by Dialoguer
public enum DialoguerDialogues{
	Generic = 0,
	OldSchoolRPG = 1,
	NextGen = 2,
	jingling = 3,
	daozei = 4,
	ashangdian = 5,
	blan = 6,
	fivehong = 7,
	elevenshangdian = 8,
	twolan = 9,
	twohong = 10,
	twelvehong = 11,
	siethinglan = 12,
	feiveteenlan = 13,
	fivenehong = 14,
	eighteengongzhu = 15,
}
