using UnityEngine;
using UnityEditor;
using System.Collections;
using System.Collections.Generic;
using DialoguerEditor;
using System.IO;
using System.Text.RegularExpressions;

public class DialoguerEnumGenerator : EditorWindow {

	[MenuItem("Dialoguer/Generate Dialogues Enum", false, 1000)]
	static public void GenerateDialoguesEnum(){
		checkDialoguerResourcesFolder();

		List<string> lines = new List<string>();
		lines.Add("// This enum was generated by Dialoguer");
		lines.Add("public enum DialoguerDialogues{");
		List<DialogueEditorDialogueObject> dialogues = DialogueEditorDataManager.data.dialogues;
		for(int i = 0; i<dialogues.Count; i+=1){
			Regex rgx = new Regex("[^a-zA-Z+$]");
			string varName = rgx.Replace(dialogues[i].name, "");
			lines.Add("\t"+varName+" = "+i+",");
		}
		lines.Add("}");

		AssetDatabase.DeleteAsset(DialogueEditorFileStatics.ENUMS_PATH + DialogueEditorFileStatics.DIALOGUE_ENUMS_FILENAME);
		File.WriteAllLines(@DialogueEditorFileStatics.ENUMS_PATH + DialogueEditorFileStatics.DIALOGUE_ENUMS_FILENAME, lines.ToArray());
		AssetDatabase.Refresh();
	}

	/*
	[MenuItem("Dialoguer/Generate Variables Enum", false, 1000)]
	static public void GenerateVariablesEnum(){
		checkDialoguerResourcesFolder();

	}

	[MenuItem("Dialoguer/Generate Themes Enum", false, 1000)]
	static public void GenerateThemesEnum(){
		checkDialoguerResourcesFolder();

	}
	*/

	private static void checkDialoguerResourcesFolder(){
		bool outputFolderExists = System.IO.Directory.Exists(@DialogueEditorFileStatics.ASSETS_FOLDER_PATH+"/"+DialogueEditorFileStatics.OUTPUT_FOLDER_PATH);
		if(!outputFolderExists) AssetDatabase.CreateFolder(DialogueEditorFileStatics.ASSETS_FOLDER_PATH, DialogueEditorFileStatics.OUTPUT_FOLDER_PATH);
		bool enumsFolderExists = System.IO.Directory.Exists(@DialogueEditorFileStatics.ASSETS_FOLDER_PATH+"/"+DialogueEditorFileStatics.OUTPUT_FOLDER_PATH+"/"+DialogueEditorFileStatics.OUTPUT_ENUMS_FOLDER_PATH);
		if(!enumsFolderExists) AssetDatabase.CreateFolder(DialogueEditorFileStatics.ASSETS_FOLDER_PATH+"/"+DialogueEditorFileStatics.OUTPUT_FOLDER_PATH, DialogueEditorFileStatics.OUTPUT_ENUMS_FOLDER_PATH);
	}
}
